name: forum

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    pull_policy: build
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - type: bind
        source: C:/Users/Josh/.aws
        target: /home/node/.aws
    environment:
      - AWS_PROFILE=admin
      - NODE_ENV=deployed