name: forum

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    pull_policy: build
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: C:/Users/Josh/.aws
        target: /home/node/.aws
    environment:
      - AWS_PROFILE=admin
      - NODE_ENV=deployed
  client:
    build:
      context: ../forum-client
      dockerfile: Dockerfile
    pull_policy: build
    ports:
      - "3001:3001"
